version: '3'

name: 'utils'

volumes:
  portainer_data:

services:
  portainer:
    image: portainer/portainer-ce:latest
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    restart: unless-stopped

  organizr:
    image: organizr/organizr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /home/lucas/home_media/organizr:/config
    ports:
    - "80:80"

  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - NET_BIND_SERVICE
      - SETUID

  librespeed:
    image: linuxserver/librespeed:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /home/lucas/home_media/librespeed:/config
    ports:
      - "9091:80"
