services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n
    #restart: unless-stopped
    networks:
      - n8n

networks:
  n8n:
    driver: bridge

volumes:
  n8n_data:

