name: "Gitea"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__DB_HOST=db:3306
      - GITEA__database__DB_NAME=gitea
      - GITEA__database__DB_USER=gitea
      - GITEA__database__DB_PASSWORD=gitea
    restart: unless-stopped
    volumes:
      - $HOME/home_server/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
