name: 'media'

services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - WEB_PORT=9090
      - PUID=1000
      - PGID=1000
    volumes:
      - $HOME/home_media/qbittorrent:/config
      - $HOME/Torrents/Downloads:/downloads
    ports:
      - '9090:9090'
      - '62609:62609'

  jackett:
    image: linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - $HOME/home_media/jackett:/config
      - $HOME/home_media/jackett/downloads:/downloads
    ports:
      - '9117:9117'

  bazarr:
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - $HOME/home_media/bazarr:/config
      - $HOME/Torrents/Animes:/animes \
      - $HOME/Torrents/Movies:/movies \
      - $HOME/Torrents/tvseries:/tv \
    ports:
      - '6767:6767'

  overseerr:
    image: linuxserver/overseerr:latest
    restart: unless-stopped
    depends_on:
      - qbittorrent
    environment:
      - TZ=America/Sao_Paulo
      - PORT=5055
    volumes:
      - $HOME/home_media/overseerr:/config
    ports:
      - '5055:5055'

  prowlarr:
    image: linuxserver/prowlarr:latest
    restart: unless-stopped
    depends_on:
      - flaresolverr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - $HOME/home_media/prowlarr:/config
    ports:
      - '9696:9696'

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    restart: unless-stopped
    volumes:
      - $HOME/home_media/flaresolverr:/config
    ports:
      - '8191:8191'

  sabnzbd:
    image: linuxserver/sabnzbd:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - $HOME/home_media/sabnzbd:/config
      - $HOME/Torrents/nzbget:/downloads
      - $HOME/Torrents/nzbget/incomplete:/incomplete-downloads
    ports:
      - '6789:6789'

  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    depends_on:
      - qbittorrent
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - $HOME/home_media/radarr:/config
      - $HOME/Torrents/Movies:/downloads
      - $HOME/Torrents/Downloads:/downloads
    ports:
      - '7878:7878'

  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    depends_on:
      - qbittorrent
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - $HOME/home_media/sonarr/config:/config
      - $HOME/Torrents/tvseries:/tv
      - $HOME/Torrents/Animes:/animes
      - $HOME/Torrents/Downloads:/downloads
    ports:
      - '8989:8989'

  plex:
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - PLEX_HW_TRAN_MAX=16
    volumes:
      - $HOME/home_media/plex:/config
      - $HOME/Torrents/Animes:/tv
      - $HOME/Torrents/tvseries:/series
      - $HOME/Torrents/Movies:/movies
    devices:
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
    network_mode: host
