name: 'kaizoku'

volumes:
  kaizoku-db:
  redis:

services:
  app:
    container_name: kaizoku
    image: ghcr.io/oae/kaizoku:latest
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://kaizoku:kaizoku@kaizoku-db:5432/kaizoku
      - KAIZOKU_PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - $HOME/home_media/kaizoku:/config
      - $HOME/Torrents/Manga/Library:/data
      - /tmp:/logs
    depends_on:
      kaizoku-db:
        condition: service_healthy
    ports:
      - '3000:3000'

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis:/data

  kaizoku-db:
    image: postgres:alpine
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U kaizoku -d kaizoku
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=kaizoku
      - POSTGRES_DB=kaizoku
      - POSTGRES_PASSWORD=kaizoku
    volumes:
      - kaizoku-db:/var/lib/postgresql/data
    ports:
      - 9099:5432

  kavita:
    image: jvmilazz0/kavita:latest
    restart: unless-stopped
    volumes:
      - $HOME/home_media/kavita:/config
      - $HOME/Torrents/Manga/Library:/manga
    ports:
      - '5000:5000'
