name: "Wallos"

services:
  wallos:
    image: bellamy/wallos:latest
    ports:
      - 8282:80
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - './db:/var/www/html/db'
      - './logos:/var/www/html/images/uploads/logos'
#    restart: unless-stopped
